"""Miscellaneous standalone CLI commands."""

from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any

import click

from tagslut.cli.commands._auth_helpers import (
    _tidal_device_login,
    _qobuz_login,
    _beatport_token_input,
)
from tagslut.cli.commands._enrich_helpers import (
    _local_file_info_from_path,
    _print_enrichment_result,
)
from tagslut.cli.runtime import (
    WRAPPER_CONTEXT,
    collect_flac_paths as _collect_flac_paths,
)

logger = logging.getLogger("tagslut")


def _raise_recovery_retired() -> None:
    raise click.ClickException(
        "tagslut.recovery is archived. Use legacy/tagslut_recovery/ for the old recovery workflow."
    )


def _default_canon_rules_path() -> Path:
    return Path(__file__).parents[3] / "tools" / "rules" / "library_canon.json"


def _write_env_file(config: dict, path: Path) -> None:  # type: ignore  # TODO: mypy-strict
    """Write configuration as .env file."""
    lines = [
        "# Dedupe Configuration",
        "# Generated by: tagslut init",
        f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "# ============================================================================",
        "# DATABASE",
        "# ============================================================================",
        f"TAGSLUT_DB={config['TAGSLUT_DB']}",
        "",
        "# ============================================================================",
        "# VOLUMES",
        "# ============================================================================",
    ]

    for key, value in sorted(config.items()):
        if key.startswith("VOLUME_"):
            lines.append(f"{key}={value}")

    lines.extend([
        "",
        "# ============================================================================",
        "# OUTPUT DIRECTORIES",
        "# ============================================================================",
        f"TAGSLUT_ARTIFACTS={config['TAGSLUT_ARTIFACTS']}",
        f"TAGSLUT_REPORTS={config['TAGSLUT_REPORTS']}",
        "",
        "# ============================================================================",
        "# SCAN SETTINGS",
        "# ============================================================================",
        f"SCAN_WORKERS={config['SCAN_WORKERS']}",
        f"SCAN_PROGRESS_INTERVAL={config['SCAN_PROGRESS_INTERVAL']}",
        f"SCAN_CHECK_INTEGRITY={str(config['SCAN_CHECK_INTEGRITY']).lower()}",
        f"SCAN_CHECK_HASH={str(config['SCAN_CHECK_HASH']).lower()}",
        f"SCAN_INCREMENTAL={str(config['SCAN_INCREMENTAL']).lower()}",
        "",
        "# ============================================================================",
        "# DECISION SETTINGS",
        "# ============================================================================",
        f"AUTO_APPROVE_THRESHOLD={config['AUTO_APPROVE_THRESHOLD']}",
        f"QUARANTINE_RETENTION_DAYS={config['QUARANTINE_RETENTION_DAYS']}",
        f"PREFER_HIGH_BITRATE={str(config['PREFER_HIGH_BITRATE']).lower()}",
        f"PREFER_HIGH_SAMPLE_RATE={str(config['PREFER_HIGH_SAMPLE_RATE']).lower()}",
        f"PREFER_VALID_INTEGRITY={str(config['PREFER_VALID_INTEGRITY']).lower()}",
        "",
    ])

    path.write_text("\n".join(lines))


def _write_toml_file(config: dict, path: Path) -> None:  # type: ignore  # TODO: mypy-strict
    """Write configuration as config.toml file."""
    lines = [
        "# Dedupe Configuration",
        "# Generated by: tagslut init",
        f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "[db]",
        f'path = "{config["TAGSLUT_DB"]}"',
        "min_disk_space_mb = 50",
        "write_sanity_check = true",
        "",
        "[library]",
        f'root = "{config["VOLUME_LIBRARY"]}"',
        "",
        "[volumes]",
    ]

    for key, value in sorted(config.items()):
        if key.startswith("VOLUME_"):
            zone = key.replace("VOLUME_", "").lower()
            lines.append(f'{zone} = "{value}"')

    lines.extend([
        "",
        "[output]",
        f'artifacts = "{config["TAGSLUT_ARTIFACTS"]}"',
        f'reports = "{config["TAGSLUT_REPORTS"]}"',
        "",
        "[scan]",
        f'workers = {config["SCAN_WORKERS"]}',
        f'progress_interval = {config["SCAN_PROGRESS_INTERVAL"]}',
        f'check_integrity = {str(config["SCAN_CHECK_INTEGRITY"]).lower()}',
        f'check_hash = {str(config["SCAN_CHECK_HASH"]).lower()}',
        f'incremental = {str(config["SCAN_INCREMENTAL"]).lower()}',
        "",
        "[decisions]",
        f'auto_approve_threshold = {config["AUTO_APPROVE_THRESHOLD"]}',
        f'quarantine_retention_days = {config["QUARANTINE_RETENTION_DAYS"]}',
        f'prefer_high_bitrate = {str(config["PREFER_HIGH_BITRATE"]).lower()}',
        f'prefer_high_sample_rate = {str(config["PREFER_HIGH_SAMPLE_RATE"]).lower()}',
        f'prefer_valid_integrity = {str(config["PREFER_VALID_INTEGRITY"]).lower()}',
        "",
    ])

    path.write_text("\n".join(lines))


def register_misc_commands(cli: click.Group) -> None:
    @cli.command("canonize", hidden=True)
    @click.argument("path", type=click.Path(exists=True))
    @click.option("--canon/--no-canon", default=True, help="Enable canonical tag rules")
    @click.option("--canon-rules", type=click.Path(exists=True), help="Path to canon rules JSON")
    @click.option("--canon-dry-run", is_flag=True, help="Print before/after diff for one file and exit")
    @click.option("--execute", is_flag=True, help="Write tags to files (default: dry-run)")
    @click.option("--limit", type=int, help="Maximum files to process")
    def canonize(path, canon, canon_rules, canon_dry_run, execute, limit):  # type: ignore  # TODO: mypy-strict
        """Apply canonical tag rules to FLAC tags using library_canon.json."""
        from tagslut.metadata.canon import load_canon_rules, write_canon_to_file

        rules_path = Path(canon_rules) if canon_rules else _default_canon_rules_path()
        rules = load_canon_rules(rules_path)

        file_paths = _collect_flac_paths(path)
        if limit:
            file_paths = file_paths[:limit]
        if not file_paths:
            click.echo("No FLAC files found.")
            return

        if canon_dry_run:
            target = file_paths[0]
            if not canon:
                click.echo("(canon disabled)")
                return
            diff = write_canon_to_file(target, rules, dry_run=True)
            if not diff:
                click.echo("(no changes)")
            else:
                for field, (old_value, new_value) in diff.items():
                    click.echo(f"{field}: {old_value!r} -> {new_value!r}")
            return

        if not execute:
            click.echo("DRY-RUN: use --execute to write tags")

        for idx, file_path in enumerate(file_paths, start=1):
            if canon:
                write_canon_to_file(file_path, rules, dry_run=not execute)
            if idx % 250 == 0 or idx == len(file_paths):
                click.echo(f"Processed {idx}/{len(file_paths)}")

    @cli.command("show-zone", hidden=True)
    @click.argument("path", type=click.Path())
    @click.option("--zones-config", type=click.Path(exists=True), help="Path to zones YAML config")
    @click.option("--config", "-c", type=click.Path(exists=True), help="Path to config.toml")
    def show_zone(path, zones_config, config):  # type: ignore  # TODO: mypy-strict
        """Show how a path is classified by ZoneManager."""
        from tagslut.utils.config import get_config
        from tagslut.zones import load_zone_manager

        cfg = get_config(Path(config)) if config else get_config()
        zone_manager = load_zone_manager(
            config=getattr(cfg, "_data", None),
            config_path=Path(zones_config) if zones_config else None,
        )
        match = zone_manager.get_zone_for_path(Path(path))

        click.echo(f"Path: {path}")
        click.echo(f"Zone: {match.zone.value}")
        click.echo(f"Zone priority: {match.zone_priority}")
        click.echo(f"Path priority: {match.path_priority}")
        click.echo(f"Matched root: {match.matched_path or '(none)'}")
        click.echo(f"Config source: {match.source}")

    @cli.command("explain-keeper", hidden=True)
    @click.option("--db", type=click.Path(), required=True, help="Database path")
    @click.option("--group-id", required=True, help="Duplicate group id (checksum)")
    @click.option("--zones-config", type=click.Path(exists=True), help="Path to zones YAML config")
    @click.option("--config", "-c", type=click.Path(exists=True), help="Path to config.toml")
    @click.option("--priority", "-p", multiple=True, help="Zone priority override order")
    @click.option("--metadata-tiebreaker", is_flag=True, help="Enable metadata tiebreaker")
    @click.option("--metadata-fields", default="artist,album,title", help="Comma-separated metadata fields")
    def explain_keeper(  # type: ignore  # TODO: mypy-strict
        db,
        group_id,
        zones_config,
        config,
        priority,
        metadata_tiebreaker,
        metadata_fields,
    ):
        """Explain keeper selection for a single duplicate group."""
        from tagslut.storage.schema import get_connection
        from tagslut.storage.queries import get_files_by_checksum
        from tagslut.storage.models import DuplicateGroup
        from tagslut.core.keeper_selection import select_keeper_for_group
        from tagslut.zones import load_zone_manager
        from tagslut.utils.config import get_config

        cfg = get_config(Path(config)) if config else get_config()
        zone_manager = load_zone_manager(
            config=getattr(cfg, "_data", None),
            config_path=Path(zones_config) if zones_config else None,
        )
        if priority:
            zone_manager = zone_manager.override_priorities(list(priority))

        fields = [f.strip() for f in metadata_fields.split(",") if f.strip()]
        conn = get_connection(db, purpose="read")
        try:
            files = get_files_by_checksum(conn, group_id)
        finally:
            conn.close()

        if not files:
            raise click.ClickException(f"No files found for group id {group_id}")

        group = DuplicateGroup(group_id=group_id, files=files, similarity=1.0, source="checksum")
        selection = select_keeper_for_group(
            group,
            zone_manager=zone_manager,
            use_metadata_tiebreaker=metadata_tiebreaker,
            metadata_fields=tuple(fields),
        )

        click.echo(f"Group: {group_id}")
        click.echo(f"Keeper: {selection.keeper.path}")  # type: ignore  # TODO: mypy-strict
        click.echo("-" * 60)
        for line in selection.explanations:
            click.echo(line)

    @cli.command("enrich-file", hidden=True)
    @click.option("--db", type=click.Path(), required=False, help="Database path")
    @click.option(
        "--file",
        "file_path",
        type=click.Path(),
        required=True,
        help="Exact file path in DB (or on disk in --standalone mode)",
    )
    @click.option("--providers", default="beatport,tidal,deezer,itunes", help="Comma-separated providers")
    @click.option("--force", is_flag=True, help="Re-process even if already enriched")
    @click.option("--retry-no-match", is_flag=True, help="Retry files previously with no match")
    @click.option("--execute", is_flag=True, help="Write updates to DB (default: dry-run)")
    @click.option("--recovery", is_flag=True, help="Recovery mode (duration health validation)")
    @click.option("--hoarding", is_flag=True, help="Hoarding mode (full metadata)")
    @click.option("--standalone", is_flag=True, help="Run without a database (read tags directly)")
    def enrich_file(  # type: ignore  # TODO: mypy-strict
        db,
        file_path,
        providers,
        force,
        retry_no_match,
        execute,
        recovery,
        hoarding,
        standalone,
    ):
        """Enrich a single file by exact path."""
        from tagslut.metadata.enricher import Enricher
        from tagslut.metadata.auth import TokenManager
        from tagslut.storage.schema import init_db
        import sqlite3

        # Determine mode (default to recovery)
        if not recovery and not hoarding:
            recovery = True
        if recovery and hoarding:
            mode = "both"
        elif recovery:
            mode = "recovery"
        else:
            mode = "hoarding"

        provider_list = [p.strip() for p in providers.split(",") if p.strip()]
        if "qobuz" in provider_list:
            raise click.ClickException("Qobuz is disabled. Remove it from --providers.")
        if "spotify" in provider_list:
            raise click.ClickException("Spotify is disabled. Remove it from --providers.")
        token_manager = TokenManager()

        if standalone:
            if db:
                raise click.ClickException("--standalone cannot be used with --db")
            file_path_obj = Path(file_path).expanduser().resolve()
            if not file_path_obj.exists():
                raise click.ClickException(f"File not found: {file_path}")
            if execute:
                click.echo("Note: --execute is ignored in standalone mode (no DB writes).")
            click.echo(f"File: {file_path_obj}")
            click.echo(f"Providers: {', '.join(provider_list)}")
            click.echo(f"Mode: {mode}")
            with Enricher(
                db_path=Path("__standalone__"),
                token_manager=token_manager,
                providers=provider_list,
                dry_run=True,
                mode=mode,
            ) as enricher:
                try:
                    file_info = _local_file_info_from_path(file_path_obj)
                except Exception as e:
                    raise click.ClickException(str(e)) from e
                result = enricher.resolve_file(file_info)
            _print_enrichment_result(result)
            click.echo("Done.")
            return

        if not db:
            raise click.ClickException("--db is required (or use --standalone)")

        # Ensure schema exists
        conn = sqlite3.connect(db)
        init_db(conn)
        conn.close()

        click.echo(f"DB: {db}")
        click.echo(f"File: {file_path}")
        click.echo(f"Providers: {', '.join(provider_list)}")
        click.echo(f"Mode: {mode}")
        if not execute:
            click.echo("DRY-RUN: no DB updates will be written")

        with Enricher(
            db_path=Path(db),
            token_manager=token_manager,
            providers=provider_list,
            dry_run=not execute,
            mode=mode,
        ) as enricher:
            enrich_result, status = enricher.enrich_file(
                str(file_path),
                force=force,
                retry_no_match=retry_no_match,
            )

        if status == "not_found":
            raise click.ClickException("File not found in database")
        if status == "not_flac_ok":
            click.echo("Skipped: file failed integrity checks (use --force to override)")
            return
        if status == "not_eligible":
            click.echo("Skipped: already enriched (use --force or --retry-no-match)")
            return
        if status == "no_match":
            click.echo("No provider match found")
            return
        if status == "failed":
            click.echo("Enrichment failed to write to database")
            return

        if enrich_result is None:
            raise click.ClickException("Expected enrichment result for successful status")
        _print_enrichment_result(enrich_result)
        click.echo("Done.")

    @cli.command("init")
    @click.option(
        '--output-format',
        type=click.Choice(['env', 'toml', 'both']),
        default='env',
        help='Configuration output format',
    )
    @click.option('--output-path', type=click.Path(), help='Custom path for config file')
    @click.option('--setup-tokens', is_flag=True, help='Also initialize tokens.json for metadata providers')
    def init(output_format, output_path, setup_tokens):  # type: ignore  # TODO: mypy-strict
        """
        Interactive initialization wizard for tagslut configuration.

        Prompts for all necessary paths, settings, and credentials needed
        for scanning and managing your music library.

        Generates configuration in .env or config.toml format.
        """
        from tagslut.metadata.auth import TokenManager, DEFAULT_TOKENS_PATH

        click.echo("")
        click.echo("╔" + "═" * 58 + "╗")
        click.echo("║" + "  TAGSLUT INITIALIZATION WIZARD".center(58) + "║")
        click.echo("╚" + "═" * 58 + "╝")
        click.echo("")
        click.echo("This wizard will help you configure tagslut for your music library.")
        click.echo("You can skip optional settings by pressing Enter.")
        click.echo("")

        config = {}

        # ========================================================================
        # SECTION 1: DATABASE
        # ========================================================================
        click.echo("─" * 60)
        click.echo("1. DATABASE CONFIGURATION")
        click.echo("─" * 60)
        click.echo("The database stores scan results, integrity checks, and metadata.")
        click.echo("")

        default_db = str(Path.home() / "tagslut" / "music.db")
        db_path = click.prompt("Database path", default=default_db, type=str)
        config["TAGSLUT_DB"] = Path(db_path).expanduser().resolve()

        # Create parent directory if needed
        if click.confirm("Create database directory if it doesn't exist?", default=True):
            config["TAGSLUT_DB"].parent.mkdir(parents=True, exist_ok=True)
            click.echo(f"  ✓ Ensured directory exists: {config['TAGSLUT_DB'].parent}")

        click.echo("")

        # ========================================================================
        # SECTION 2: VOLUME PATHS
        # ========================================================================
        click.echo("─" * 60)
        click.echo("2. VOLUME PATHS")
        click.echo("─" * 60)
        click.echo("Volumes are physical directories where your music files are stored.")
        click.echo("Zones are logical categories (e.g., accepted, staging, quarantine).")
        click.echo("")

        # Required: Library volume
        click.echo("PRIMARY LIBRARY (required)")
        click.echo("  Main collection of accepted/canonical music files")
        while True:
            library = click.prompt("  Library path", type=str)
            library_path = Path(library).expanduser().resolve()
            if library_path.is_dir():
                config["VOLUME_LIBRARY"] = library_path
                click.echo(f"  ✓ {library_path}")
                break
            click.echo(f"  ✗ Directory not found: {library}. Try again.")
        click.echo("")

        # Optional volumes
        optional_volumes = {
            "VOLUME_STAGING": ("Staging area", "Files being processed/reviewed"),
            "VOLUME_ARCHIVE": ("Archive", "Historical backups or older versions"),
            "VOLUME_INBOX": ("Inbox", "New/incoming files to be processed"),
            "VOLUME_SUSPECT": ("Suspect", "Files with integrity issues"),
            "VOLUME_REJECTED": ("Rejected", "Rejected/unwanted files"),
            "VOLUME_QUARANTINE": ("Quarantine", "Files marked for deletion"),
            "VOLUME_RECOVERY": ("Recovery", "Recovery target for salvaged files"),
            "VOLUME_VAULT": ("Vault", "External backup/vault location"),
        }

        for var_name, (short_name, description) in optional_volumes.items():
            click.echo(f"{short_name.upper()} (optional)")
            click.echo(f"  {description}")
            volume = click.prompt(f"  {short_name} path (press Enter to skip)", default="", type=str)
            if volume:
                volume_path = Path(volume).expanduser().resolve()
                if volume_path.is_dir():
                    config[var_name] = volume_path
                    click.echo(f"  ✓ {volume_path}")
                else:
                    click.echo(f"  ⚠ Directory not found: {volume} (skipped)")
            click.echo("")

        # ========================================================================
        # SECTION 3: OUTPUT DIRECTORIES
        # ========================================================================
        click.echo("─" * 60)
        click.echo("3. OUTPUT DIRECTORIES")
        click.echo("─" * 60)
        click.echo("Where to save reports, logs, and artifacts.")
        click.echo("")

        default_artifacts = str(Path.cwd() / "artifacts")
        artifacts = click.prompt("Artifacts directory", default=default_artifacts, type=str)
        config["TAGSLUT_ARTIFACTS"] = Path(artifacts).expanduser().resolve()

        default_reports = str(config["TAGSLUT_ARTIFACTS"] / "reports")
        reports = click.prompt("Reports directory", default=default_reports, type=str)
        config["TAGSLUT_REPORTS"] = Path(reports).expanduser().resolve()

        # Create directories
        if click.confirm("Create output directories if they don't exist?", default=True):
            config["TAGSLUT_ARTIFACTS"].mkdir(parents=True, exist_ok=True)
            config["TAGSLUT_REPORTS"].mkdir(parents=True, exist_ok=True)
            click.echo(f"  ✓ Created: {config['TAGSLUT_ARTIFACTS']}")
            click.echo(f"  ✓ Created: {config['TAGSLUT_REPORTS']}")

        click.echo("")

        # ========================================================================
        # SECTION 4: SCAN SETTINGS
        # ========================================================================
        click.echo("─" * 60)
        click.echo("4. SCAN SETTINGS")
        click.echo("─" * 60)
        click.echo("Performance and validation options for scanning.")
        click.echo("")

        cpu_count = os.cpu_count() or 4
        recommended_workers = max(4, cpu_count - 2)

        workers = click.prompt(
            f"Parallel workers (CPU cores: {cpu_count}, recommended: {recommended_workers})",
            default=recommended_workers,  # type: ignore  # TODO: mypy-strict
            type=int
        )
        config["SCAN_WORKERS"] = workers

        check_integrity = click.confirm(
            "Run FLAC integrity checks (flac -t)? Slower but thorough",
            default=True
        )
        config["SCAN_CHECK_INTEGRITY"] = check_integrity  # type: ignore  # TODO: mypy-strict

        check_hash = click.confirm(
            "Calculate SHA256 hashes? Slower but enables deduplication",
            default=True
        )
        config["SCAN_CHECK_HASH"] = check_hash  # type: ignore  # TODO: mypy-strict

        incremental = click.confirm(
            "Use incremental scanning? (Skip already-scanned files)",
            default=True
        )
        config["SCAN_INCREMENTAL"] = incremental  # type: ignore  # TODO: mypy-strict

        progress_interval = click.prompt(
            "Progress report interval (files)",
            default=100,  # type: ignore  # TODO: mypy-strict
            type=int
        )
        config["SCAN_PROGRESS_INTERVAL"] = progress_interval

        click.echo("")

        # ========================================================================
        # SECTION 5: DECISION SETTINGS
        # ========================================================================
        click.echo("─" * 60)
        click.echo("5. DECISION SETTINGS")
        click.echo("─" * 60)
        click.echo("Preferences for duplicate resolution and quality.")
        click.echo("")

        auto_approve = click.prompt(
            "Auto-approve threshold (0.0-1.0, higher = more conservative)",
            default=0.95,  # type: ignore  # TODO: mypy-strict
            type=float
        )
        config["AUTO_APPROVE_THRESHOLD"] = auto_approve

        quarantine_days = click.prompt(
            "Quarantine retention days (before eligible for deletion)",
            default=30,  # type: ignore  # TODO: mypy-strict
            type=int
        )
        config["QUARANTINE_RETENTION_DAYS"] = quarantine_days

        config["PREFER_HIGH_BITRATE"] = click.confirm(  # type: ignore  # TODO: mypy-strict
            "Prefer high bitrate when deduplicating?",
            default=True
        )

        config["PREFER_HIGH_SAMPLE_RATE"] = click.confirm(  # type: ignore  # TODO: mypy-strict
            "Prefer high sample rate when deduplicating?",
            default=True
        )

        config["PREFER_VALID_INTEGRITY"] = click.confirm(  # type: ignore  # TODO: mypy-strict
            "Prefer files with valid integrity?",
            default=True
        )

        click.echo("")

        # ========================================================================
        # SECTION 6: METADATA PROVIDERS (OPTIONAL)
        # ========================================================================
        if setup_tokens or click.confirm("Configure metadata providers for enrichment?", default=False):
            click.echo("")
            click.echo("─" * 60)
            click.echo("6. METADATA PROVIDER AUTHENTICATION")
            click.echo("─" * 60)
            click.echo("External services for fetching BPM, key, genre, ISRC, etc.")
            click.echo("")

            token_manager = TokenManager()

            # Initialize tokens file if needed
            if not DEFAULT_TOKENS_PATH.exists():
                token_manager.init_template()
                click.echo(f"✓ Created tokens template: {DEFAULT_TOKENS_PATH}")

            click.echo("Available providers:")
            click.echo("  • Spotify    - Client credentials (get from developer.spotify.com)")
            click.echo("  • Beatport   - Manual token extraction (requires DJ account)")
            click.echo("  • Tidal      - Device authorization (requires subscription)")
            click.echo("  • Qobuz      - Email/password login (requires account)")
            click.echo("  • iTunes     - No authentication needed (public API)")
            click.echo("")

            if click.confirm("Set up Spotify?", default=False):
                click.echo("Get credentials from: https://developer.spotify.com/dashboard")
                client_id = click.prompt("  Spotify Client ID", type=str)
                client_secret = click.prompt("  Spotify Client Secret", type=str, hide_input=True)
                # Update Spotify credentials in tokens
                if "spotify" not in token_manager._tokens:
                    token_manager._tokens["spotify"] = {}
                token_manager._tokens["spotify"]["client_id"] = client_id
                token_manager._tokens["spotify"]["client_secret"] = client_secret
                token_manager._save_tokens()
                click.echo("  ✓ Spotify configured")
                click.echo("")

            if click.confirm("Set up Tidal?", default=False):
                _tidal_device_login(token_manager)
                click.echo("")

            if click.confirm("Set up Qobuz?", default=False):
                _qobuz_login(token_manager)
                click.echo("")

            if click.confirm("Set up Beatport?", default=False):
                _beatport_token_input(token_manager)
                click.echo("")

            click.echo(f"✓ Token configuration saved to: {DEFAULT_TOKENS_PATH}")
            click.echo("")

        # ========================================================================
        # SUMMARY & CONFIRMATION
        # ========================================================================
        click.echo("═" * 60)
        click.echo("CONFIGURATION SUMMARY")
        click.echo("═" * 60)
        click.echo("")
        click.echo("DATABASE:")
        click.echo(f"  {config['TAGSLUT_DB']}")
        click.echo("")
        click.echo("VOLUMES:")
        for key, value in config.items():
            if key.startswith("VOLUME_"):
                zone_name = key.replace("VOLUME_", "").lower().title()
                click.echo(f"  {zone_name:12} → {value}")
        click.echo("")
        click.echo("OUTPUT:")
        click.echo(f"  Artifacts    → {config['TAGSLUT_ARTIFACTS']}")
        click.echo(f"  Reports      → {config['TAGSLUT_REPORTS']}")
        click.echo("")
        click.echo("SCAN SETTINGS:")
        click.echo(f"  Workers:     {config['SCAN_WORKERS']}")
        click.echo(f"  Integrity:   {config['SCAN_CHECK_INTEGRITY']}")
        click.echo(f"  Hash:        {config['SCAN_CHECK_HASH']}")
        click.echo(f"  Incremental: {config['SCAN_INCREMENTAL']}")
        click.echo("")
        click.echo("DECISION SETTINGS:")
        click.echo(f"  Auto-approve:    {config['AUTO_APPROVE_THRESHOLD']}")
        click.echo(f"  Quarantine days: {config['QUARANTINE_RETENTION_DAYS']}")
        click.echo(f"  Prefer hi-res:   {config['PREFER_HIGH_BITRATE']} / {config['PREFER_HIGH_SAMPLE_RATE']}")
        click.echo("")
        click.echo("═" * 60)

        if not click.confirm("Save this configuration?", default=True):
            click.echo("Aborted.")
            raise click.Abort()

        # ========================================================================
        # WRITE CONFIGURATION
        # ========================================================================
        click.echo("")

        if output_format in ('env', 'both'):
            env_path = Path(output_path) if output_path and output_format == 'env' else Path.cwd() / ".env"
            _write_env_file(config, env_path)
            click.echo(f"✓ Saved environment config: {env_path}")
            click.echo("")
            click.echo("To use this configuration:")
            click.echo(f"  export $(cat {env_path} | xargs)")
            click.echo("  OR add to your ~/.bashrc or ~/.zshrc:")
            click.echo(f"  source {env_path}")
            click.echo("")

        if output_format in ('toml', 'both'):
            toml_path = Path(output_path) if output_path and output_format == 'toml' else Path.cwd() / "config.toml"
            _write_toml_file(config, toml_path)
            click.echo(f"✓ Saved TOML config: {toml_path}")
            click.echo("")
            click.echo("To use this configuration:")
            click.echo(f"  export TAGSLUT_CONFIG={toml_path}")
            click.echo("")

        click.echo("═" * 60)
        click.echo("INITIALIZATION COMPLETE!")
        click.echo("═" * 60)
        click.echo("")
        click.echo("Next steps:")
        click.echo("  1. Review your configuration file")
        click.echo("  2. Register/index your library:")
        click.echo(f"     tagslut index register {config['VOLUME_LIBRARY']} --source legacy")
        click.echo("  3. Build a deterministic plan:")
        click.echo("     tagslut decide plan --policy library_balanced --input candidates.json")
        click.echo("")

    @cli.command(name="_recover", hidden=True, context_settings=WRAPPER_CONTEXT)
    @click.argument("args", nargs=-1, type=click.UNPROCESSED)
    def recover(args: Any) -> None:
        """
        Retired compatibility wrapper for the archived recovery workflow.
        """
        del args
        _raise_recovery_retired()

    @cli.command("recovery", hidden=True, context_settings=WRAPPER_CONTEXT)
    @click.argument("args", nargs=-1, type=click.UNPROCESSED)
    def recovery(args):  # type: ignore  # TODO: mypy-strict
        """
        Retired compatibility wrapper for the archived recovery workflow.
        """
        del args
        _raise_recovery_retired()
