rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Angelo Ferreri/(2022) JACKIN HOUSE Collection 3/Angelo Ferreri - (2022) JACKIN HOUSE Collection 3 - 33. Music Owns Me  (Radio Edit) (1).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Disclosure/(2020) ENERGY/Disclosure - (2020) ENERGY - 01-05. Douha (Mali Mali).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Armand van Helden feat. Duane Harden/(1999) You Don't Know Me (single)/Armand van Helden feat. Duane Harden - (1999) You Don't Know Me (single) - 01. You Don't Know Me (radio edit) (1).flac"
rm -v "/Volumes/Vault/RECOVERED_TRASH/Future Disco - (XXXX) Future Disco Poolside Sounds 9 - 15. More Cowbell (Extended Mix) (dup 1).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Chet Faker/(2012) Thinking in Textures EP/Chet Faker - (2012) Thinking in Textures EP - 03. No Diggity (1).flac"
rm -v "/Volumes/Vault/RECOVERED_TRASH/Future Disco - (XXXX) Future Disco Poolside Sounds 9 - 10. Sweet Nightmare (Extended Mix) (dup 1).flac"
rm -v "/Volumes/Vault/RC2/Bon Iver - (2008) For Emma, Forever Ago - 03. Skinny Love.flac 09-23-31-123.flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Bon Iver/(2008) For Emma, Forever Ago/Bon Iver - (2008) For Emma, Forever Ago - 03. Skinny Love (2).flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Bon Iver/(2016) 22, a Million/Bon Iver - (2016) 22, a Million - 09. ____45_____ (1).flac"
rm -v "/Volumes/Vault/Vault/SAD_CONSOLIDATION_071432/Bon Iver/(2016) 22, a Million/Bon Iver - (2016) 22, a Million - 09. ____45_____.fixed.flac"
rm -v "/Volumes/Vault/Vault/SAD_QUARANTINE_CONSOLIDATION_071432/Taylor McFerrin/(2014) Early Riser/Taylor McFerrin - (2014) Early Riser - 07. Already There (1).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Azla/(2021) Nebula (single)/Azla - (2021) Nebula (single) - 01. Nebula (1).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Crazy P/(2015) Walk Dance Talk Sing Remixes, Part 2 EP/Crazy P - (2015) Walk Dance Talk Sing Remixes, Part 2 EP - 01. Echo (Luke Solomon's Body mix).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/BDB, Bicep, Benjamin Damage/(2024) CHROMA 005 A.L.O.E/BDB, Bicep, Benjamin Damage - (2024) CHROMA 005 A.L.O.E - 01. CHROMA 005 A.L.O.E.flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Rinky Dinky/(2021) Alligators And Crocodiles (single)/Rinky Dinky - (2021) Alligators And Crocodiles (single) - 01. Alligators And Crocodiles.flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Bon Iver/(2020) Blood Bank EP/Bon Iver - (2020) Blood Bank EP - 03. Babys (2).flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Bon Iver/(2025) SABLE, fABLE/Bon Iver - (2025) SABLE, fABLE - 02. S P E Y S I D E (2).flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Smooth Touch/(1993) House of Love (single)/Smooth Touch - (1993) House of Love (single) - 01. House of Love (Love mix).flac"
rm -v "/Volumes/Vault/RECOVERED_TRASH/Argy - (2005) Love Dose EP - 03. Love Dose (Luciano remix).flac 09-23-31-135.flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Bon Iver/(2020) Blood Bank EP/Bon Iver - (2020) Blood Bank EP - 04. Woods (2).flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Bon Iver/(2011) Bon Iver, Bon Iver/Bon Iver - (2011) Bon Iver, Bon Iver - 03. Holocene (2).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Armen Kusikian & Fairuz/(XXXX) Música y Show Árabe/Armen Kusikian & Fairuz - (XXXX) Música y Show Árabe - 10. Wentab (1).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Angelo Ferreri/(2022) JACKIN HOUSE Collection/Angelo Ferreri - (2022) JACKIN HOUSE Collection - 12. That's The Way  (Angelo Ferreri Remix) (1).flac"
rm -v "/Volumes/Vault/RC2/Bon Iver - (2008) For Emma, Forever Ago - 09. re: stacks.flac 09-23-30-957.flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Bon Iver/(2008) For Emma, Forever Ago/Bon Iver - (2008) For Emma, Forever Ago - 09. re: stacks (2).flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Charlotte de Witte/(2023) Power of Thought EP/Charlotte de Witte - (2023) Power of Thought EP - 02. Pria (2).flac"
rm -v "/Volumes/Vault/RECOVERED_TRASH/Future Disco - (XXXX) Future Disco Poolside Sounds 9 - 19. Dima (Mixed).fixed (dup 1).flac"
rm -v "/Volumes/Vault/Vault/SAD_QUARANTINE_CONSOLIDATION_071432/Alsarah & the Nubatones/(2016) Manara/Alsarah & the Nubatones - (2016) Manara - 02. Asilah Interlude (1).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Anna Lunoe/(2022) Saturday Love/Anna Lunoe - (2022) Saturday Love - 05. Peach Fuzz (1).flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Bon Iver/(2025) SABLE, fABLE/Bon Iver - (2025) SABLE, fABLE - 11. There's a Rhythmn (2).flac"
rm -v "/Volumes/Vault/Vault/ORIGINAL_DUPLICATES/20251007_053210/Bon Iver/(2007) For Emma, Forever Ago/Bon Iver - (2007) For Emma, Forever Ago - 08. For Emma.flac"
rm -v "/Volumes/Vault/RECOVERED_TRASH/Cassius - (2016) Au Rêve - 02. The Sound of Violence (1) (dup 1).flac"
rm -v "/Volumes/Vault/Vault/CORRUPTED_ORIGINALS/Volumes/dotad/MUSIC/Blood Orange feat. The Durutti Column, Tariq Al-Sabir, Caroline Polachek & Daniel Caesar/(2025) The Field (single)/Blood Orange feat. The Durutti Column, Tariq Al-Sabir, Caroline Polachek & Daniel Caesar - (2025) The Field (single) - 01. The Field.flac"
rm -v "/Volumes/Vault/Vault/DUPEGURU/Bon Iver/(2011) Bon Iver, Bon Iver/Bon Iver - (2011) Bon Iver, Bon Iver - 01. Perth (2).flac"
