"""Command-line interface for the dedupe toolkit."""

from __future__ import annotations

import argparse
import csv
import logging
import sqlite3
import sys
from pathlib import Path
from typing import Iterable, Optional, Set

from . import manifest, matcher, rstudio_parser, scanner

# Ensure we load the local `dedupe` package when running from the repo tree.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

LOGGER = logging.getLogger(__name__)


def _configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )


def _path(value: str) -> Path:
    return Path(value).expanduser()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="dedupe",
        description="Audio recovery toolkit",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging output",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # ------------------------------------------------------------------
    # scan-library
    # ------------------------------------------------------------------
    scan_parser = subparsers.add_parser(
        "scan-library",
        help="Scan an audio library and write metadata to SQLite",
    )
    scan_parser.add_argument(
        "--root",
        type=_path,
        required=True,
        help="Root directory to scan",
    )
    scan_parser.add_argument(
        "--out",
        type=_path,
        required=True,
        help="SQLite database path to populate",
    )
    scan_parser.add_argument(
        "--fingerprints",
        action="store_true",
        help=(
            "Capture optional Chromaprint fingerprints (requires fpcalc; "
            "skipped automatically when unavailable)"
        ),
    )
    scan_parser.add_argument(
        "--resume",
        action="store_true",
        help=(
            "Resume a previous scan by skipping unchanged files present in "
            "the database (size + mtime check)"
        ),
    )
    scan_parser.add_argument(
        "--progress",
        action="store_true",
        help="Show a progress bar during scanning",
    )
    scan_parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of parallel workers to use (default: 1)",
    )

    # ------------------------------------------------------------------
    # parse-rstudio
    # ------------------------------------------------------------------
    parse_parser = subparsers.add_parser(
        "parse-rstudio",
        help="Parse an R-Studio Recognized Files export into SQLite",
    )
    parse_parser.add_argument(
        "--input",
        type=_path,
        required=True,
        help="R-Studio export path",
    )
    parse_parser.add_argument(
        "--out",
        type=_path,
        required=True,
        help="SQLite database to store recovery candidates",
    )

    # ------------------------------------------------------------------
    # match
    # ------------------------------------------------------------------
    match_parser = subparsers.add_parser(
        "match",
        help="Match scanned library metadata with recovery candidates",
    )
    match_parser.add_argument(
        "--library",
        type=_path,
        required=True,
        help="Library SQLite database",
    )
    match_parser.add_argument(
        "--recovered",
        type=_path,
        required=True,
        help="Recovered files SQLite database",
    )
    match_parser.add_argument(
        "--out",
        type=_path,
        required=True,
        help="CSV file to write match results",
    )

    # ------------------------------------------------------------------
    # generate-manifest
    # ------------------------------------------------------------------
    manifest_parser = subparsers.add_parser(
        "generate-manifest",
        help="Create a recovery manifest from match results",
    )
    manifest_parser.add_argument(
        "--matches",
        type=_path,
        required=True,
        help="CSV file produced by the match command",
    )
    manifest_parser.add_argument(
        "--out",
        type=_path,
        required=True,
        help="Destination CSV for the recovery manifest",
    )

    # ------------------------------------------------------------------
    # verify-manifest
    # ------------------------------------------------------------------
    verify_parser = subparsers.add_parser(
        "verify-manifest",
        help=(
            "Validate a manifest against library.db and recovered.db. "
            "Lists all problems (missing paths, duplicates, etc.)."
        ),
    )
    verify_parser.add_argument(
        "manifest",
        type=_path,
        help="Path to manifest CSV (generated by generate-manifest)",
    )
    verify_parser.add_argument(
        "--library-db",
        type=_path,
        default=Path("artifacts/db/library.db"),
        help="Path to library SQLite DB (default: artifacts/db/library.db)",
    )
    verify_parser.add_argument(
        "--recovered-db",
        type=_path,
        default=Path("artifacts/db/recovered.db"),
        help="Path to recovered SQLite DB (default: artifacts/db/recovered.db)",
    )

    return parser


def _command_scan(args: argparse.Namespace) -> int:
    total = scanner.scan(
        root=args.root,
        database=args.out,
        include_fingerprints=args.fingerprints,
        resume=getattr(args, "resume", False),
        show_progress=getattr(args, "progress", False),
        workers=getattr(args, "workers", 1),
    )
    LOGGER.info("Indexed %s files", total)
    return 0


def _command_parse_rstudio(args: argparse.Namespace) -> int:
    records = list(rstudio_parser.parse_export(args.input))
    count = rstudio_parser.load_into_database(records, args.out)
    LOGGER.info("Captured %s recovery candidates", count)
    return 0


def _command_match(args: argparse.Namespace) -> int:
    matcher.match_databases(args.library, args.recovered, args.out)
    return 0


def _command_manifest(args: argparse.Namespace) -> int:
    manifest.generate_manifest(args.matches, args.out)
    return 0


# ----------------------------------------------------------------------
# verify-manifest implementation
# ----------------------------------------------------------------------


def _load_column_values(
    db_path: Path,
    table: str,
    column: str,
) -> Set[str]:
    """Return a set of non-NULL values from table.column in db_path."""
    values: Set[str] = set()
    conn = sqlite3.connect(str(db_path))
    try:
        conn.row_factory = sqlite3.Row
        cur = conn.execute(f"SELECT {column} FROM {table}")
        for row in cur:
            val = row[column]
            if val is not None:
                values.add(str(val))
    finally:
        conn.close()
    return values


def _command_verify_manifest(args: argparse.Namespace) -> int:
    manifest_path: Path = args.manifest
    library_db: Path = args.library_db
    recovered_db: Path = args.recovered_db

    print("=== VERIFYING MANIFEST ===")

    # 0) Basic file / DB existence checks
    if not manifest_path.is_file():
        print(f"ERROR: Manifest file not found: {manifest_path}")
        return 1
    if not library_db.is_file():
        print(f"ERROR: Library DB not found: {library_db}")
        return 1
    if not recovered_db.is_file():
        print(f"ERROR: Recovered DB not found: {recovered_db}")
        return 1

    # 1) Load DB path sets
    print("[1/4] Loading path sets from databases...")
    try:
        lib_paths_db = _load_column_values(
            library_db,
            table="library_files",
            column="path",
        )
    except sqlite3.Error as exc:
        print(f"ERROR: Failed to read library_files from {library_db}: {exc}")
        return 1

    try:
        rec_paths_db = _load_column_values(
            recovered_db,
            table="recovered_files",
            column="source_path",
        )
    except sqlite3.Error as exc:
        print(
            f"ERROR: Failed to read recovered_files from {recovered_db}: {exc}",
        )
        return 1

    print(
        f"    Library paths loaded:   {len(lib_paths_db)}\n"
        f"    Recovered paths loaded: {len(rec_paths_db)}",
    )

    # 2) Read manifest CSV and walk rows
    print("[2/4] Scanning manifest rows...")

    missing_lib_paths: Set[str] = set()
    missing_rec_paths: Set[str] = set()
    empty_rec_paths: Set[str] = set()
    empty_lib_paths: Set[str] = set()
    duplicate_lib_paths: Set[str] = set()
    seen_lib_paths: Set[str] = set()

    total_rows = 0

    with manifest_path.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        fieldnames = reader.fieldnames or []
        required = {"library_path", "recovered_path"}

        if not required.issubset(set(fieldnames)):
            print("ERROR: Manifest is missing required columns.")
            print(f"       Required: {sorted(required)}")
            print(f"       Found:    {fieldnames}")
            return 1

        for row in reader:
            total_rows += 1
            lib_path = (row.get("library_path") or "").strip()
            rec_path = (row.get("recovered_path") or "").strip()

            # Track empties separately (do not assume they are DB errors)
            if not lib_path:
                empty_lib_paths.add(lib_path)
            if not rec_path:
                empty_rec_paths.add(lib_path)

            # Only DB-check non-empty paths
            if lib_path:
                if lib_path not in lib_paths_db:
                    missing_lib_paths.add(lib_path)
                if lib_path in seen_lib_paths:
                    duplicate_lib_paths.add(lib_path)
                else:
                    seen_lib_paths.add(lib_path)

            if rec_path:
                if rec_path not in rec_paths_db:
                    missing_rec_paths.add(rec_path)

    print(f"    Manifest rows inspected: {total_rows}")

    # 3) Summarise findings
    print("[3/4] Summary:")

    if missing_lib_paths:
        print(f"    Missing library paths in DB: {len(missing_lib_paths)}")
    else:
        print("    ✓ All non-empty library paths exist in library.db")

    if missing_rec_paths:
        print(f"    Missing recovered paths in DB: {len(missing_rec_paths)}")
    else:
        print("    ✓ All non-empty recovered paths exist in recovered.db")

    if duplicate_lib_paths:
        print(f"    Duplicate library_path entries: {len(duplicate_lib_paths)}")
    else:
        print("    ✓ No duplicate library_path entries in manifest")

    if empty_rec_paths:
        print(
            f"    Rows with empty recovered_path (unrecoverable entries): "
            f"{len(empty_rec_paths)}",
        )
    else:
        print("    ✓ No rows with empty recovered_path")

    if empty_lib_paths:
        print(
            f"    Rows with empty library_path: {len(empty_lib_paths)} "
            "(should normally be 0)",
        )
    else:
        print("    ✓ No rows with empty library_path")

    # 4) Detailed error listing (option B: list all problems)
    print("[4/4] Detailed problems (if any):")

    any_errors = False

    if missing_lib_paths:
        any_errors = True
        print("\n-- Library paths present in manifest but missing in library.db:")
        for p in sorted(missing_lib_paths):
            print(p)

    if missing_rec_paths:
        any_errors = True
        print("\n-- Recovered paths present in manifest but missing in recovered.db:")
        for p in sorted(missing_rec_paths):
            print(p)

    if duplicate_lib_paths:
        any_errors = True
        print("\n-- library_path values that appear more than once in manifest:")
        for p in sorted(duplicate_lib_paths):
            print(p)

    if not any_errors:
        print("✓ No structural problems detected. Manifest is consistent.")

    print("=== VERIFY MANIFEST COMPLETE ===")

    # Non-zero exit when there are real errors
    return 1 if any_errors else 0


COMMAND_HANDLERS = {
    "scan-library": _command_scan,
    "parse-rstudio": _command_parse_rstudio,
    "match": _command_match,
    "generate-manifest": _command_manifest,
    "verify-manifest": _command_verify_manifest,
}


def main(argv: Optional[Iterable[str]] = None) -> int:
    parser = build_parser()

    # Allow callers to place global options (like --verbose) either before
    # or after the subcommand. argparse supports `parse_intermixed_args`
    # (Python 3.8+) which accepts intermixed options; fall back to the
    # regular `parse_args` when it's not available.
    arglist = list(argv) if argv is not None else list(sys.argv[1:])

    # Normalise placement of a small set of known global options so users can
    # place them after the subcommand.
    if arglist:
        first_pos = None
        for i, a in enumerate(arglist):
            if not a.startswith("-"):
                first_pos = i
                break
        if first_pos is not None:
            globals_to_move = ["--verbose"]
            for opt in globals_to_move:
                if opt in arglist[first_pos + 1:]:
                    while opt in arglist:
                        arglist.remove(opt)
                    arglist.insert(0, opt)

    if hasattr(parser, "parse_intermixed_args"):
        try:
            args = parser.parse_intermixed_args(arglist)
        except (TypeError, ValueError):
            args = parser.parse_args(arglist)
    else:
        args = parser.parse_args(arglist)

    _configure_logging(args.verbose)
    handler = COMMAND_HANDLERS[args.command]
    return handler(args)


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())