import sys
import json
import click
import logging
from pathlib import Path

# Ensure imports work
sys.path.insert(0, str(Path(__file__).parents[2]))

from dedupe.core.actions import delete_file
from dedupe.utils.cli_helper import common_options, configure_execution

@click.command()
@click.argument("plan_file", type=click.Path(exists=True, dir_okay=False))
@click.option("--dry-run/--execute", default=True, help="Simulate actions (default) or actually delete files")
@common_options
def apply(plan_file, dry_run, verbose, config):
    """
    Executes a deduplication plan generated by 'recommend'.
    """
    configure_execution(verbose, config)
    logger = logging.getLogger("dedupe")
    
    with open(plan_file, "r") as f:
        data = json.load(f)
        
    groups = data.get("plan", [])
    logger.info(f"Loaded plan with {len(groups)} groups.")
    
    stats = {"kept": 0, "dropped": 0, "reviewed": 0, "errors": 0}

    if dry_run:
        click.secho("--- DRY RUN MODE: No files will be touched ---", fg="yellow")

    for group in groups:
        for decision in group["decisions"]:
            path = Path(decision["path"])
            action = decision["action"]
            
            if action == "DROP":
                if decision["confidence"] == "LOW":
                    logger.warning(f"Skipping LOW confidence DROP for {path}")
                    stats["reviewed"] += 1
                    continue

                success, msg = delete_file(path, dry_run=dry_run)
                if success:
                    stats["dropped"] += 1
                else:
                    stats["errors"] += 1
                    
            elif action == "KEEP":
                stats["kept"] += 1
                
            elif action == "REVIEW":
                logger.info(f"Skipping REVIEW item: {path}")
                stats["reviewed"] += 1

    click.echo("
--- Execution Summary ---")
    click.echo(f"Kept: {stats['kept']}")
    click.echo(f"Dropped: {stats['dropped']}")
    click.echo(f"Left for Review: {stats['reviewed']}")
    click.echo(f"Errors: {stats['errors']}")

if __name__ == "__main__":
    apply()
