$kind: http-example
request:
  url: "{{baseUrl}}/search/v1/charts?q=string&count=20&genre_id=string&genre_name\
    =string&is_approved=true&from_publish_date=1965-12-27&to_publish_date=1965-\
    12-27"
  method: GET
  headers:
    - key: Accept
      value: application/json
    - key: Authorization
      value: Bearer <token>
      description: "Added as a part of security scheme: bearer"
  queryParams:
    - key: q
      value: string
      description: Search query text
    - key: count
      value: "20"
      description: The number of results returned in the response
    - key: genre_id
      value: string
      description: >
        
        Returns tracks that have the genre of the ID inputed. Multiple genre IDs
        can be added

        by separating them with a comma, ex: (89, 6, 14).


        For a list of available genres and their IDs, make a GET call to our API
        route /catalog/genres/
    - key: genre_name
      value: string
      description: >
        
        Returns tracks that have a genre which partially matches the value
        inputed.


        For ex: “Techno” would return tracks with a genre of “Hard Techno”,
        “Techno (Peak Time / Driving)”, etc.


        For a list of genres and their names, make a GET call to our API route
        /catalog/genres/
    - key: is_approved
      value: "true"
      description: >
        
        When TRUE, the response will only include charts that have been
        approved.


        When FALSE, the response will include all charts.


        It is recommended to leave this set to TRUE
    - key: from_publish_date
      value: 1965-12-27
      description: |
        
        The date a chart was published on Beatport.com or Beatsource.com.

        Format: YYYY-MM-DD
    - key: to_publish_date
      value: 1965-12-27
      description: |
        
        The date a chart was published on Beatport.com or Beatsource.com.

        Format: YYYY-MM-DD
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "data": [
          {
            "score": 3034.344208043219,
            "chart_id": 2789,
            "chart_name": "string",
            "create_date": "string",
            "is_approved": 3169,
            "update_date": "string",
            "enabled": 8108,
            "is_indexed": 2609,
            "is_published": 3083,
            "artist_id": 3772,
            "artist_name": null,
            "person_id": null,
            "publish_date": null,
            "item_type_id": null,
            "person_username": "string",
            "track_count": null,
            "chart_image_uri": "string",
            "chart_image_dynamic_uri": null,
            "genres": [
              {
                "genre_id": 8746,
                "genre_name": "string"
              },
              {
                "genre_id": null,
                "genre_name": null
              }
            ]
          },
          {
            "score": 819.8504251769157,
            "chart_id": 4170,
            "chart_name": "string",
            "create_date": "string",
            "is_approved": 9193,
            "update_date": "string",
            "enabled": 783,
            "is_indexed": 9325,
            "is_published": 3526,
            "artist_id": 8229,
            "artist_name": null,
            "person_id": null,
            "publish_date": null,
            "item_type_id": null,
            "person_username": "string",
            "track_count": 7095,
            "chart_image_uri": "string",
            "chart_image_dynamic_uri": "string",
            "genres": [
              {
                "genre_id": 4949,
                "genre_name": null
              },
              {
                "genre_id": null,
                "genre_name": "string"
              }
            ]
          }
        ],
        "debug": {},
        "explain": null
      }
order: 1000
