begin;

create schema if not exists public;

create table if not exists public.asset_file (
    id bigint generated by default as identity primary key,
    path text not null unique,
    content_sha256 text,
    streaminfo_md5 text,
    checksum text,
    size_bytes bigint,
    mtime double precision,
    duration_s double precision,
    duration_measured_ms integer,
    sample_rate integer,
    bit_depth integer,
    bitrate integer,
    library text,
    zone text,
    download_source text,
    download_date text,
    mgmt_status text,
    flac_ok boolean,
    integrity_state text,
    integrity_checked_at timestamptz,
    sha256_checked_at timestamptz,
    streaminfo_checked_at timestamptz,
    first_seen_at timestamptz default now(),
    last_seen_at timestamptz default now(),
    chromaprint_fingerprint text,
    chromaprint_duration_s double precision
);

create table if not exists public.track_identity (
    id bigint generated by default as identity primary key,
    identity_key text not null unique,
    isrc text,
    beatport_id text,
    tidal_id text,
    qobuz_id text,
    spotify_id text,
    apple_music_id text,
    deezer_id text,
    traxsource_id text,
    itunes_id text,
    musicbrainz_id text,
    artist_norm text,
    title_norm text,
    album_norm text,
    canonical_title text,
    canonical_artist text,
    canonical_album text,
    canonical_genre text,
    canonical_sub_genre text,
    canonical_label text,
    canonical_catalog_number text,
    canonical_mix_name text,
    canonical_duration double precision,
    canonical_year integer,
    canonical_release_date text,
    canonical_bpm double precision,
    canonical_key text,
    canonical_payload_json jsonb,
    enriched_at timestamptz,
    duration_ref_ms integer,
    ref_source text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    merged_into_id bigint references public.track_identity(id)
);

create table if not exists public.asset_link (
    id bigint generated by default as identity primary key,
    asset_id bigint not null unique references public.asset_file(id) on delete cascade,
    identity_id bigint not null references public.track_identity(id),
    confidence double precision,
    link_source text,
    active boolean not null default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.library_track_sources (
    id bigint generated by default as identity primary key,
    identity_key text not null references public.track_identity(identity_key) on delete cascade,
    provider text not null,
    provider_track_id text not null,
    source_url text,
    match_confidence text,
    raw_payload_json jsonb,
    metadata_json jsonb,
    fetched_at timestamptz default now(),
    unique(identity_key, provider, provider_track_id)
);

create table if not exists public.move_plan (
    id bigint generated by default as identity primary key,
    plan_key text not null unique,
    plan_type text,
    plan_path text,
    policy_version text,
    context_json jsonb,
    created_at timestamptz default now()
);

create table if not exists public.move_execution (
    id bigint generated by default as identity primary key,
    plan_id bigint references public.move_plan(id),
    asset_id bigint references public.asset_file(id),
    source_path text,
    dest_path text,
    action text,
    status text not null,
    verification text,
    error text,
    details_json jsonb,
    executed_at timestamptz default now()
);

create table if not exists public.provenance_event (
    id bigint generated by default as identity primary key,
    event_type text not null,
    event_time timestamptz default now(),
    asset_id bigint references public.asset_file(id),
    identity_id bigint references public.track_identity(id),
    move_plan_id bigint references public.move_plan(id),
    move_execution_id bigint references public.move_execution(id),
    source_path text,
    dest_path text,
    status text,
    details_json jsonb
);

create table if not exists public.scan_runs (
    id bigint generated by default as identity primary key,
    mode text not null default 'queue' check (mode = 'queue'),
    library_root text,
    status text not null default 'pending',
    created_at timestamptz default now(),
    started_at timestamptz,
    completed_at timestamptz,
    tool_versions_json jsonb,
    metadata_json jsonb
);

create table if not exists public.scan_queue (
    id bigint generated by default as identity primary key,
    run_id bigint not null references public.scan_runs(id) on delete cascade,
    path text not null,
    size_bytes bigint,
    mtime_ns bigint,
    stage text not null default 'discover',
    state text not null default 'PENDING',
    last_error text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    unique(run_id, path)
);

create table if not exists public.scan_issues (
    id bigint generated by default as identity primary key,
    run_id bigint not null references public.scan_runs(id) on delete cascade,
    queue_id bigint references public.scan_queue(id) on delete set null,
    path text,
    issue_code text not null,
    severity text not null default 'INFO',
    evidence_json jsonb,
    created_at timestamptz default now()
);

create table if not exists public.schema_migrations (
    id bigint primary key,
    schema_name text not null,
    version integer not null,
    applied_at timestamptz default now(),
    note text,
    unique(schema_name, version)
);

create table if not exists public.migration_progress (
    id integer primary key check (id = 1),
    v2_path text not null,
    v3_path text not null,
    batch_size integer not null,
    last_v2_rowid bigint not null default 0,
    last_v2_path text,
    assets_migrated integer not null default 0,
    identities_created integer not null default 0,
    unidentified_count integer not null default 0,
    integrity_preserved_count integer not null default 0,
    enrichment_preserved_count integer not null default 0,
    library_sources_done integer not null default 0,
    move_tables_done integer not null default 0,
    is_complete boolean not null default false,
    started_at timestamptz default now(),
    updated_at timestamptz default now(),
    completed_at timestamptz
);

create table if not exists public.identity_merge_log (
    id bigint generated by default as identity primary key,
    merged_at timestamptz default now(),
    merge_type text not null,
    key_value text not null,
    winner_identity_id bigint not null references public.track_identity(id),
    loser_identity_ids text not null,
    assets_moved integer not null,
    fields_copied_json jsonb,
    rationale_json jsonb,
    dry_run boolean not null default false
);

create table if not exists public.preferred_asset (
    identity_id bigint primary key references public.track_identity(id),
    asset_id bigint not null references public.asset_file(id),
    score double precision not null,
    reason_json jsonb not null,
    version integer not null,
    computed_at timestamptz default now()
);

create table if not exists public.file_quarantine (
    id bigint primary key,
    original_path text not null,
    quarantine_path text not null,
    sha256 text,
    keeper_path text,
    source_zone text,
    reason text,
    tier text,
    plan_id text,
    quarantined_at timestamptz not null,
    deleted_at timestamptz,
    delete_reason text
);

create table if not exists public.track_duration_refs (
    ref_id text primary key,
    ref_type text not null,
    duration_ref_ms integer not null,
    ref_source text not null,
    ref_updated_at timestamptz
);

create table if not exists public.promotions (
    id bigint generated by default as identity primary key,
    source_path text not null unique,
    dest_path text not null,
    mode text not null,
    timestamp timestamptz not null
);

create table if not exists public.library_tracks (
    id bigint generated by default as identity primary key,
    library_track_key text unique,
    title text,
    artist text,
    album text,
    duration_ms integer,
    isrc text,
    release_date text,
    explicit boolean,
    best_cover_url text,
    lyrics_excerpt text,
    genre text,
    bpm double precision,
    musical_key text,
    label text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.scan_sessions (
    id bigint primary key,
    started_at timestamptz default now(),
    ended_at timestamptz,
    finished_at timestamptz,
    db_path text,
    library text,
    zone text,
    root_path text,
    paths_source text,
    paths_from_file text,
    scan_integrity boolean,
    scan_hash boolean,
    recheck boolean,
    incremental boolean,
    force_all boolean,
    discovered integer,
    considered integer,
    skipped integer,
    updated integer,
    succeeded integer,
    failed integer,
    scan_limit integer,
    status text,
    host text
);

create table if not exists public.file_scan_runs (
    id bigint primary key,
    session_id bigint not null references public.scan_sessions(id),
    path text not null,
    mtime double precision,
    size bigint,
    streaminfo_md5 text,
    streaminfo_checked_at timestamptz,
    sha256 text,
    sha256_checked_at timestamptz,
    flac_ok boolean,
    integrity_state text,
    integrity_checked_at timestamptz,
    outcome text,
    checked_metadata boolean,
    checked_integrity boolean,
    checked_hash boolean,
    checked_streaminfo boolean,
    error_class text,
    error_message text,
    created_at timestamptz default now()
);

create table if not exists public.gig_sets (
    id bigint generated by default as identity primary key,
    name text not null,
    filter_expr text,
    usb_path text,
    manifest_path text,
    track_count integer default 0,
    created_at timestamptz default now(),
    exported_at timestamptz
);

create table if not exists public.gig_set_tracks (
    id bigint generated by default as identity primary key,
    gig_set_id bigint not null references public.gig_sets(id),
    file_path text not null,
    mp3_path text,
    usb_dest_path text,
    transcoded_at timestamptz,
    exported_at timestamptz,
    rekordbox_id integer
);

create table if not exists public.file_metadata_archive (
    checksum text primary key,
    first_seen_at timestamptz not null,
    first_seen_path text not null,
    raw_tags_json jsonb not null,
    technical_json jsonb not null,
    durations_json jsonb not null,
    isrc_candidates_json jsonb not null,
    fingerprint_json jsonb,
    identity_confidence integer not null,
    quality_rank integer
);

create table if not exists public.file_path_history (
    id bigint generated by default as identity primary key,
    checksum text not null,
    path text not null,
    first_seen_at timestamptz not null,
    last_seen_at timestamptz not null
);

create table if not exists public.scan_trust_batches (
    id bigint generated by default as identity primary key,
    created_at timestamptz,
    root_path text,
    trust_pre integer,
    trust_post integer,
    allow_accepted boolean,
    db_path text
);

create table if not exists public.identity_status (
    identity_id bigint primary key references public.track_identity(id),
    status text not null check (status in ('active', 'orphan', 'archived', 'curated')),
    reason_json jsonb not null default '{}'::jsonb,
    version integer not null,
    computed_at timestamptz not null default now()
);

create table if not exists public.files (
    path text primary key,
    library text,
    zone text,
    mtime double precision,
    size bigint,
    checksum text,
    streaminfo_md5 text,
    sha256 text,
    duration double precision,
    bit_depth integer,
    sample_rate integer,
    bitrate integer,
    metadata_json jsonb,
    flac_ok boolean,
    integrity_state text,
    integrity_checked_at timestamptz,
    streaminfo_checked_at timestamptz,
    sha256_checked_at timestamptz,
    acoustid text,
    recovery_status text,
    recovery_method text,
    backup_path text,
    recovered_at timestamptz,
    new_duration double precision,
    duration_delta double precision,
    pcm_md5 text,
    silence_events integer,
    verified_at timestamptz,
    canonical_title text,
    canonical_artist text,
    canonical_album text,
    canonical_isrc text,
    canonical_duration double precision,
    canonical_duration_source text,
    canonical_year integer,
    canonical_release_date text,
    canonical_bpm double precision,
    canonical_key text,
    canonical_genre text,
    canonical_sub_genre text,
    canonical_label text,
    canonical_catalog_number text,
    canonical_mix_name text,
    canonical_explicit boolean,
    canonical_energy double precision,
    canonical_danceability double precision,
    canonical_valence double precision,
    canonical_acousticness double precision,
    canonical_instrumentalness double precision,
    canonical_loudness double precision,
    canonical_album_art_url text,
    spotify_id text,
    beatport_id text,
    tidal_id text,
    qobuz_id text,
    itunes_id text,
    deezer_id text,
    traxsource_id text,
    musicbrainz_id text,
    enriched_at timestamptz,
    enrichment_providers text,
    enrichment_confidence text,
    metadata_health text,
    metadata_health_reason text,
    library_track_key text,
    download_source text,
    download_date text,
    original_path text,
    mgmt_status text,
    fingerprint text,
    m3u_exported text,
    m3u_path text,
    is_dj_material boolean default false,
    duration_ref_ms integer,
    duration_ref_source text,
    duration_ref_track_id text,
    duration_ref_updated_at timestamptz,
    duration_measured_ms integer,
    duration_measured_at timestamptz,
    duration_delta_ms integer,
    duration_status text,
    duration_check_version text,
    dj_pool_path text,
    quality_rank integer,
    rekordbox_id integer,
    last_exported_usb text,
    dj_flag boolean default false,
    bpm double precision,
    key_camelot text,
    energy integer,
    genre text,
    isrc text,
    scan_status text,
    scan_flags_json jsonb,
    actual_duration double precision,
    identity_confidence integer,
    isrc_candidates_json jsonb,
    duplicate_of_checksum text,
    last_scanned_at timestamptz,
    scan_stage_reached integer,
    checksum_type text,
    dj_set_role text,
    dj_subrole text
);

create table if not exists public.dj_track_profile (
    identity_id bigint primary key references public.track_identity(id),
    rating integer check (rating between 0 and 5),
    energy integer check (energy between 0 and 10),
    set_role text check (set_role in ('warmup','builder','peak','tool','closer','ambient','break','unknown')),
    dj_tags_json jsonb not null default '[]'::jsonb,
    notes text,
    last_played_at timestamptz,
    updated_at timestamptz not null default now()
);

create table if not exists public.tag_hoard_runs (
    run_id bigint generated by default as identity primary key,
    created_at timestamptz,
    roots_json jsonb,
    extensions_json jsonb,
    scanned_files integer,
    max_files integer,
    workers integer,
    max_value_len integer
);

create table if not exists public.tag_hoard_keys (
    run_id bigint references public.tag_hoard_runs(run_id) on delete cascade,
    tag text,
    files_with_tag integer,
    unique_values integer,
    primary key (run_id, tag)
);

create table if not exists public.tag_hoard_values (
    run_id bigint references public.tag_hoard_runs(run_id) on delete cascade,
    tag text,
    value text,
    count integer,
    primary key (run_id, tag, value)
);

create table if not exists public.tag_hoard_files (
    run_id bigint references public.tag_hoard_runs(run_id) on delete cascade,
    path text,
    tags_json jsonb
);

create table if not exists public.migrations_applied (
    id bigint primary key,
    name text unique,
    applied_at timestamptz
);

create table if not exists public.asset_analysis (
    id bigint generated by default as identity primary key,
    asset_id bigint not null references public.asset_file(id) on delete cascade,
    analyzer text not null,
    analyzer_version text not null,
    analysis_scope text not null,
    bpm double precision,
    musical_key text,
    analysis_energy_1_10 integer check (analysis_energy_1_10 between 1 and 10),
    confidence double precision,
    raw_payload_json jsonb,
    computed_at timestamptz not null default now(),
    unique(asset_id, analysis_scope)
);

create table if not exists public.gigs (
    id bigint generated by default as identity primary key,
    date text not null,
    venue text,
    bpm_min integer,
    bpm_max integer,
    roles_filter text,
    track_count integer,
    output_path text,
    created_at timestamptz default now()
);

create table if not exists public.mp3_asset (
    id bigint generated by default as identity primary key,
    identity_id bigint references public.track_identity(id),
    asset_id bigint references public.asset_file(id),
    path text not null unique,
    content_sha256 text,
    size_bytes bigint,
    bitrate integer,
    sample_rate integer,
    duration_s double precision,
    profile text not null default 'standard',
    status text not null default 'unverified' check (status in ('unverified','verified','missing','superseded')),
    source text not null default 'unknown',
    zone text,
    transcoded_at timestamptz,
    reconciled_at timestamptz,
    lexicon_track_id integer,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.dj_admission (
    id bigint generated by default as identity primary key,
    identity_id bigint unique references public.track_identity(id),
    mp3_asset_id bigint references public.mp3_asset(id),
    status text not null default 'pending' check (status in ('pending','admitted','rejected','needs_review')),
    source text not null default 'unknown',
    notes text,
    admitted_at timestamptz,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.dj_track_id_map (
    id bigint generated by default as identity primary key,
    dj_admission_id bigint unique references public.dj_admission(id),
    rekordbox_track_id integer not null unique,
    assigned_at timestamptz default now()
);

create table if not exists public.dj_playlist (
    id bigint generated by default as identity primary key,
    name text not null,
    parent_id bigint references public.dj_playlist(id),
    lexicon_playlist_id integer,
    sort_key text,
    playlist_type text default 'standard',
    created_at timestamptz default now(),
    unique(name, parent_id)
);

create table if not exists public.dj_playlist_track (
    playlist_id bigint not null references public.dj_playlist(id) on delete cascade,
    dj_admission_id bigint not null references public.dj_admission(id) on delete cascade,
    ordinal integer not null,
    primary key (playlist_id, dj_admission_id)
);

create table if not exists public.dj_export_state (
    id bigint generated by default as identity primary key,
    kind text not null,
    output_path text not null,
    manifest_hash text,
    scope_json jsonb,
    emitted_at timestamptz default now()
);

create table if not exists public.reconcile_log (
    id bigint generated by default as identity primary key,
    run_id text not null,
    event_time timestamptz default now(),
    source text not null,
    action text not null,
    confidence text,
    mp3_path text,
    identity_id bigint,
    lexicon_track_id integer,
    details_json jsonb
);

create index if not exists idx_asset_file_sha256 on public.asset_file(content_sha256);
create index if not exists idx_asset_file_streaminfo_md5 on public.asset_file(streaminfo_md5);
create index if not exists idx_asset_file_checksum on public.asset_file(checksum);
create index if not exists idx_asset_file_integrity_state on public.asset_file(integrity_state);
create index if not exists idx_asset_file_chromaprint on public.asset_file(chromaprint_fingerprint);
create index if not exists idx_asset_file_chromaprint_duration on public.asset_file(chromaprint_duration_s);

create index if not exists idx_track_identity_key on public.track_identity(identity_key);
create index if not exists idx_track_identity_isrc on public.track_identity(isrc);
create index if not exists idx_track_identity_beatport on public.track_identity(beatport_id);
create index if not exists idx_track_identity_tidal on public.track_identity(tidal_id);
create index if not exists idx_track_identity_qobuz on public.track_identity(qobuz_id);
create index if not exists idx_track_identity_spotify on public.track_identity(spotify_id);
create index if not exists idx_track_identity_apple_music on public.track_identity(apple_music_id);
create index if not exists idx_track_identity_deezer on public.track_identity(deezer_id);
create index if not exists idx_track_identity_traxsource on public.track_identity(traxsource_id);
create index if not exists idx_track_identity_itunes on public.track_identity(itunes_id);
create index if not exists idx_track_identity_musicbrainz on public.track_identity(musicbrainz_id);
create index if not exists idx_track_identity_merged_into on public.track_identity(merged_into_id);

create index if not exists idx_asset_link_identity on public.asset_link(identity_id);
create index if not exists idx_asset_link_asset on public.asset_link(asset_id);

create index if not exists idx_library_track_sources_identity_key on public.library_track_sources(identity_key);
create index if not exists idx_library_track_sources_provider_id on public.library_track_sources(provider, provider_track_id);

create index if not exists idx_move_execution_plan on public.move_execution(plan_id);
create index if not exists idx_move_execution_asset on public.move_execution(asset_id);
create index if not exists idx_move_execution_status on public.move_execution(status);
create index if not exists idx_move_execution_dest on public.move_execution(dest_path);

create index if not exists idx_provenance_event_type on public.provenance_event(event_type);
create index if not exists idx_provenance_event_asset on public.provenance_event(asset_id);
create index if not exists idx_provenance_event_move_exec on public.provenance_event(move_execution_id);
create index if not exists idx_provenance_event_event on public.provenance_event(event_type);

create index if not exists idx_scan_queue_run_state on public.scan_queue(run_id, state);
create index if not exists idx_scan_queue_stage on public.scan_queue(stage);
create index if not exists idx_scan_issues_code on public.scan_issues(issue_code);

create index if not exists idx_identity_merge_log_key_value on public.identity_merge_log(key_value);

create index if not exists idx_preferred_asset_asset_id on public.preferred_asset(asset_id);
create index if not exists idx_preferred_asset_version on public.preferred_asset(version);
create index if not exists idx_preferred_asset_identity on public.preferred_asset(identity_id);

create index if not exists idx_file_quarantine_quarantined_at on public.file_quarantine(quarantined_at);
create index if not exists idx_file_quarantine_deleted_at on public.file_quarantine(deleted_at);
create index if not exists idx_file_quarantine_sha256 on public.file_quarantine(sha256);

create index if not exists idx_track_duration_refs_type on public.track_duration_refs(ref_type);

create index if not exists idx_promotions_source on public.promotions(source_path);
create index if not exists idx_promotions_timestamp on public.promotions(timestamp);

create index if not exists idx_library_tracks_isrc on public.library_tracks(isrc);
create index if not exists idx_library_tracks_key on public.library_tracks(library_track_key);

create index if not exists idx_scan_sessions_started_at on public.scan_sessions(started_at);
create index if not exists idx_file_scan_runs_session on public.file_scan_runs(session_id);
create index if not exists idx_file_scan_runs_path on public.file_scan_runs(path);

create index if not exists idx_gig_sets_name on public.gig_sets(name);
create index if not exists idx_gig_sets_exported_at on public.gig_sets(exported_at);
create index if not exists idx_gig_set_tracks_set on public.gig_set_tracks(gig_set_id);
create index if not exists idx_gig_set_tracks_file on public.gig_set_tracks(file_path);

create index if not exists idx_archive_confidence on public.file_metadata_archive(identity_confidence);
create index if not exists idx_path_history_checksum on public.file_path_history(checksum);

create index if not exists idx_identity_status_status on public.identity_status(status);
create index if not exists idx_identity_status_version on public.identity_status(version);
create index if not exists idx_identity_status_identity on public.identity_status(identity_id);

create index if not exists idx_checksum on public.files(checksum);
create index if not exists idx_acoustid on public.files(acoustid);
create index if not exists idx_streaminfo_md5 on public.files(streaminfo_md5);
create index if not exists idx_sha256 on public.files(sha256);
create index if not exists idx_recovery_status on public.files(recovery_status);
create index if not exists idx_integrity_state on public.files(integrity_state);
create index if not exists idx_enriched_at on public.files(enriched_at);
create index if not exists idx_canonical_isrc on public.files(canonical_isrc);
create index if not exists idx_download_source on public.files(download_source);
create index if not exists idx_mgmt_status on public.files(mgmt_status);
create index if not exists idx_fingerprint on public.files(fingerprint);
create index if not exists idx_original_path on public.files(original_path);
create index if not exists idx_files_path on public.files(path);
create index if not exists idx_files_mtime on public.files(mtime);
create index if not exists idx_files_path_mtime on public.files(path, mtime);
create index if not exists idx_is_dj_material on public.files(is_dj_material);
create index if not exists idx_duration_status on public.files(duration_status);
create index if not exists idx_duration_ref_track_id on public.files(duration_ref_track_id);
create index if not exists idx_quality_rank on public.files(quality_rank);
create index if not exists idx_dj_pool_path on public.files(dj_pool_path);
create index if not exists idx_last_exported_usb on public.files(last_exported_usb);
create index if not exists idx_dj_flag on public.files(dj_flag);
create index if not exists idx_bpm on public.files(bpm);
create index if not exists idx_key_camelot on public.files(key_camelot);
create index if not exists idx_isrc on public.files(isrc);
create index if not exists idx_rekordbox_id on public.files(rekordbox_id);
create index if not exists idx_files_duration_mtime on public.files(duration_status, mtime);
create index if not exists idx_files_duration_source_mtime on public.files(duration_status, download_source, mtime);
create index if not exists idx_library_track_key on public.files(library_track_key);
create index if not exists idx_dj_set_role on public.files(dj_set_role);
create index if not exists idx_dj_subrole on public.files(dj_subrole);

create index if not exists idx_dj_track_profile_set_role on public.dj_track_profile(set_role);
create index if not exists idx_dj_track_profile_energy on public.dj_track_profile(energy);
create index if not exists idx_dj_track_profile_last_played_at on public.dj_track_profile(last_played_at);
create index if not exists idx_dj_profile_identity on public.dj_track_profile(identity_id);

create index if not exists idx_asset_analysis_asset on public.asset_analysis(asset_id);
create index if not exists idx_asset_analysis_scope on public.asset_analysis(analysis_scope, computed_at);

create index if not exists idx_gigs_date on public.gigs(date);
create index if not exists idx_gigs_created_at on public.gigs(created_at);

create index if not exists idx_mp3_asset_identity on public.mp3_asset(identity_id);
create index if not exists idx_mp3_asset_zone on public.mp3_asset(zone);
create index if not exists idx_mp3_asset_lexicon on public.mp3_asset(lexicon_track_id);
create index if not exists idx_mp3_asset_path on public.mp3_asset(path);
create index if not exists idx_mp3_asset_status on public.mp3_asset(status);

create index if not exists idx_dj_admission_identity on public.dj_admission(identity_id);
create index if not exists idx_dj_admission_status on public.dj_admission(status);

create index if not exists idx_dj_export_state_kind on public.dj_export_state(kind);

create index if not exists idx_reconcile_log_run on public.reconcile_log(run_id);
create index if not exists idx_reconcile_log_identity on public.reconcile_log(identity_id);

create or replace view public.v_active_identity as
select ti.*
from public.track_identity ti
join public.identity_status ist
  on ist.identity_id = ti.id
where ti.merged_into_id is null
  and ist.status = 'active';

create or replace view public.v_dj_ready_candidates as
select
    ti.id as identity_id,
    ti.identity_key as identity_key,
    ti.canonical_artist as artist,
    ti.canonical_title as title,
    ti.canonical_bpm as bpm,
    ti.canonical_key as key,
    ti.canonical_genre as genre,
    ti.canonical_duration as duration_s,
    pa.asset_id as preferred_asset_id,
    af.path as preferred_path,
    coalesce(ist.status, 'unknown') as status,
    dj.rating as rating,
    dj.energy as energy,
    dj.set_role as set_role,
    dj.dj_tags_json as dj_tags_json,
    dj.notes as notes,
    dj.last_played_at as last_played_at
from public.track_identity ti
left join public.identity_status ist on ist.identity_id = ti.id
left join public.preferred_asset pa on pa.identity_id = ti.id
left join public.asset_file af on af.id = pa.asset_id
left join public.dj_track_profile dj on dj.identity_id = ti.id
where ti.merged_into_id is null;

create or replace view public.v_dj_pool_candidates_v3 as
select
    ti.id as identity_id,
    ti.identity_key as identity_key,
    ti.isrc as isrc,
    ti.beatport_id as beatport_id,
    ti.canonical_artist as artist,
    ti.canonical_title as title,
    ti.canonical_album as album,
    ti.canonical_mix_name as mix_name,
    ti.canonical_genre as genre,
    ti.canonical_sub_genre as sub_genre,
    ti.canonical_bpm as bpm,
    ti.canonical_key as musical_key,
    coalesce(ti.canonical_duration, af.duration_s) as duration_s,
    ist.status as identity_status,
    pa.asset_id as preferred_asset_id,
    af.path as asset_path,
    af.mtime as asset_mtime,
    af.content_sha256 as sha256,
    af.sample_rate as sample_rate,
    af.bit_depth as bit_depth,
    af.bitrate as bitrate,
    af.integrity_state as integrity_state,
    af.integrity_checked_at as integrity_checked_at,
    af.first_seen_at as first_seen_at,
    af.last_seen_at as last_seen_at,
    dj.rating as dj_rating,
    dj.energy as dj_energy,
    dj.set_role as dj_set_role,
    dj.dj_tags_json as dj_tags_json,
    dj.last_played_at as dj_last_played_at,
    dj.notes as dj_notes,
    dj.updated_at as dj_updated_at,
    ti.enriched_at as identity_enriched_at,
    ti.created_at as identity_created_at,
    ti.updated_at as identity_updated_at,
    ti.merged_into_id as merged_into_id
from public.track_identity ti
left join public.identity_status ist on ist.identity_id = ti.id
left join public.preferred_asset pa on pa.identity_id = ti.id
left join public.asset_file af on af.id = pa.asset_id
left join public.dj_track_profile dj on dj.identity_id = ti.id
where ti.merged_into_id is null;

create or replace view public.v_dj_pool_candidates_active_v3 as
select *
from public.v_dj_pool_candidates_v3
where preferred_asset_id is not null
  and identity_status in ('curated', 'active');

create or replace view public.v_dj_pool_candidates_active_orphan_v3 as
select *
from public.v_dj_pool_candidates_v3
where preferred_asset_id is not null
  and identity_status in ('curated', 'active', 'orphan');

create or replace view public.v_asset_analysis_latest_dj as
select *
from public.asset_analysis
where analysis_scope = 'dj';

create or replace view public.v_dj_export_metadata_v1 as
select
    ti.id as identity_id,
    ti.identity_key as identity_key,
    ti.isrc as isrc,
    ti.canonical_artist as artist,
    ti.canonical_title as title,
    ti.canonical_album as album,
    ti.canonical_genre as genre,
    ti.canonical_label as label,
    ti.canonical_year as year,
    pa.asset_id as preferred_asset_id,
    af.path as preferred_path,
    coalesce(ti.canonical_bpm, aa.bpm) as export_bpm,
    case
        when ti.canonical_bpm is not null then 'identity'
        when aa.bpm is not null then 'analysis'
        else null
    end as bpm_source,
    coalesce(ti.canonical_key, aa.musical_key) as export_key,
    case
        when ti.canonical_key is not null then 'identity'
        when aa.musical_key is not null then 'analysis'
        else null
    end as key_source,
    coalesce(dj.energy, aa.analysis_energy_1_10) as export_energy,
    case
        when dj.energy is not null then 'dj_profile'
        when aa.analysis_energy_1_10 is not null then 'analysis'
        else null
    end as energy_source,
    aa.analyzer as analysis_analyzer,
    aa.computed_at as analysis_computed_at
from public.track_identity ti
left join public.preferred_asset pa on pa.identity_id = ti.id
left join public.asset_file af on af.id = pa.asset_id
left join public.dj_track_profile dj on dj.identity_id = ti.id
left join public.v_asset_analysis_latest_dj aa on aa.asset_id = pa.asset_id
where ti.merged_into_id is null;

commit;
