import sys
import json
import click
import logging
from pathlib import Path

# Ensure imports work
sys.path.insert(0, str(Path(__file__).parents[2]))

from tagslut.utils import env_paths
from tagslut.utils.cli_helper import common_options, configure_execution

@click.command()
@click.argument("plan_file_arg", type=click.Path(exists=True, dir_okay=False), required=False)
@click.option("--input", "-i", "plan_file_opt", type=click.Path(exists=True, dir_okay=False), help="Input plan file (default: $TAGSLUT_REPORTS/plan.json)")
@click.option("--confirm", is_flag=True, help="Actually execute the actions (disables dry-run).")
@common_options
def apply(plan_file_arg: str | None, plan_file_opt: str | None, confirm: bool, verbose: bool, config: str | None) -> None:
    """
    Executes a deduplication plan generated by 'recommend'.
    """
    configure_execution(verbose, config)
    logger = logging.getLogger("tagslut")

    plan_file = plan_file_opt or plan_file_arg
    if not plan_file:
        default_plan = env_paths.get_reports_dir() / "plan.json"
        if default_plan.exists():
            plan_file = str(default_plan)
        else:
            raise click.UsageError("Please provide a plan file via argument or --input.")

    dry_run = not confirm
    with open(plan_file, "r") as f:
        data = json.load(f)

    groups = data.get("plan", [])
    logger.info(f"Loaded plan with {len(groups)} groups.")

    stats = {"kept": 0, "dropped": 0, "reviewed": 0, "errors": 0}

    if dry_run:
        click.secho("--- DRY RUN MODE: No files will be touched ---", fg="yellow")

    for group in groups:
        for decision in group["decisions"]:
            path = Path(decision["path"])
            action = decision["action"]

            # SAFETY LOCK: This was hardcoded to block all DROP actions.
            # We keep it as a safety measure but make it clearer.
            if action == "DROP":
                # To enable deletions, the user should explicitly set an env var
                # or we can move this to a CLI flag later.
                import os
                if os.getenv("TAGSLUT_ALLOW_DROP") != "1":
                    logger.warning("Skipping DROP action for %s (COMMUNE is review-first). Set DEDUPE_ALLOW_DROP=1 to enable.", path)
                    stats["reviewed"] += 1
                    continue
                else:
                    # Actually DROP logic would go here if implemented
                    # For now, it's still not implemented in this script
                    logger.info("DROP action for %s allowed but not yet implemented in apply.py", path)
                    stats["dropped"] += 1
                    continue

            elif action == "KEEP":
                stats["kept"] += 1

            elif action == "REVIEW":
                logger.info(f"Skipping REVIEW item: {path}")
                stats["reviewed"] += 1

    click.echo("\n--- Execution Summary ---")
    click.echo(f"Kept: {stats['kept']}")
    click.echo(f"Dropped: {stats['dropped']}")
    click.echo(f"Left for Review: {stats['reviewed']}")
    click.echo(f"Errors: {stats['errors']}")

if __name__ == "__main__":
    apply()
